language: dart
sudo: false

dart: 
  - stable

addons:
  sauce_connect: true

before_install:
  - export WEBDRIVER_SERVER=http://$SAUCE_USERNAME:$SAUCE_ACCESS_KEY@ondemand.saucelabs.com/wd/hub/

script: ./tool/travis.sh
