language: dart
# This is necessary to use proper Chrome. Travis's version of chromium is from
# 2014.
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  firefox: latest

dart:
  - dev
  # Re-enable stable when the stable version of Dart is >= 2.0.0
  #- stable

with_content_shell: false

matrix:
  allow_failures:
    - dart: dev

before_install:
  - export CHROMEDRIVER_BINARY=/usr/bin/google-chrome
  - export CHROMEDRIVER_ARGS=--no-sandbox
  - /usr/bin/google-chrome --version
  - firefox --version

  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - wget http://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - export PATH=$PATH:$PWD
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz
  - tar -xvzf geckodriver-v0.19.1-linux64.tar.gz
  - export PATH=$PATH:$PWD
  - ./tool/travis-setup.sh

script:
  - ./tool/travis.sh
