name: webdriver
version: 0.10.0-pre.9
author: Marc Fisher II <fisherii@google.com>
description: >
  Provides WebDriver bindings for Dart. These use the WebDriver JSON interface,
  and as such, require the use of the WebDriver remote server.
homepage: https://github.com/google/webdriver.dart
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  analyzer: '^0.25.0+1'
  args: '^0.13.0'
  crypto: '^0.9.0'
  matcher: '^0.12.0'
  path: '^1.3.5'
  pool: '^1.0.1'
  shelf: '^0.6.1+1'
  shelf_static: '^0.2.2'
  shelf_web_socket: '^0.0.1+2'
  stack_trace: '^1.3.2'
  test: '^0.12.0'
  yaml: '^2.1.2'
