name: webdriver
version: 1.2.3
author: Marc Fisher II <fisherii@google.com>
description: >
  Provides WebDriver bindings for Dart. These use the WebDriver JSON interface,
  and as such, require the use of the WebDriver remote server.
homepage: https://github.com/google/webdriver.dart
environment:
  sdk: '>=1.21.1 <2.0.0'
dependencies:
  archive: '^1.0.0'
  matcher: '^0.12.0'
  path: '^1.3.0'
  stack_trace: '^1.3.0'
  unittest: '^0.11.6'
dev_dependencies:
  test: '^0.12.3'
