name: webdriver
version: 2.0.0-beta
authors: Marc Fisher II <fisherii@google.com>, Matt Staats<staats@google.com>
description: >
  Provides WebDriver bindings for Dart. These support the WebDriver JSON interface
  and the W3C spec and require the use of the WebDriver remote server.
homepage: https://github.com/google/webdriver.dart
environment:
  sdk: '>=1.24.0 <2.0.0'
dependencies:
  archive: '^1.0.0'
  matcher: '^0.12.0'
  path: '^1.3.0'
  stack_trace: '^1.3.0'
  sync_http: "^0.1.1"
  unittest: '^0.11.6'
dev_dependencies:
  test: '^0.12.3'
