name: webdriver
version: 0.7.5
author: Dart Team <misc@dartlang.org>
description: Provides WebDriver bindings for Dart. These use the WebDriver JSON interface, and as such, require the use of the WebDriver remote server.
homepage: https://github.com/dart-lang/webdriver
environment:
  sdk: '>=0.6.21+3'
dependencies:
  crypto: '>=0.6.21+3'
  meta: '>=0.6.21+3'
dev_dependencies:
  path: '>=0.6.21+3'
  unittest: '>=0.6.21+3'
